[package]
name = "wikinota_backend"
version = "0.0.1"
authors = ["i5heu <i5h@i5h.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gerasdb]
path = "../../GerasDB"